### ISSUE TITLE
users are not active, when setting active = true and gets deleted when I set active = 1,

### ISSUE THREAD

**Issue by theoneandonly-vector** [myOmikron/mailcow-ldap-sync#2]
I found the real issue..

As I'm not familiar with mailcow.. I never checked if the users are active..
That was the problem @login.

So the issue:
when I define "active" = true, the user gets created but "active" is set to "0".
when I define "active" = 1, the user gets deleted.

**Comment by myOmikron** [comment]
Do you set these values in the config? If so, the script will search for a field in the LDAP with the given value. As there are no such fields, the script will default to set the users not active. 

If you have a field that handles the active option, enter the username, otherwise just leave the field empty. All users are set to active then.

**Comment by theoneandonly-vector** [comment]
thank you so much :)
it works now.. I filtered the users if my value is active (true).. so when I set it to "1" it won't see him becaus eof my filter..
